### ISSUE TITLE
【修正依頼】ディレクトリ階層

### ISSUE THREAD

**Issue by mihye1128** [nehiro/animeb#24]
現在リポジトリの中の`animeb-app`の中で展開されていますが、リポジトリの直下に移動させてください。

**Comment by nehiro** [comment]
こちらはvscodeで普通に移動させて問題ないでしょうか？

**Comment by mihye1128** [comment]
はい！問題ありません 👍

**Comment by nehiro** [comment]
ありがとうございます！うまくいったと思います！
